---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 30m
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  targetNamespace: kyverno
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: '2.5.x'
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
