---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 60m0s
  wait: true
  timeout: 3m0s
  retryInterval: 2m0s
  force: true
  path: ./infrastructure/demo/kyverno
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
